version: '3'

services:
  roki-fd:
    build: .
    image: roki-fd
    command: /bin/bash -c "cd roki-fd/example/chain && make arm_box_test && ./arm_box_test && rk_anim ../model/arm_2DoF.ztk arm.zvs ../model/box.ztk box.zvs -env ../model/floor.ztk"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
