name: CI-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3  
      - name: setup env
        run: |
          echo "PREFIX=${HOME}/usr/" >> $GITHUB_ENV
          echo "PATH=$PATH:${HOME}/usr/bin" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/usr/lib" >> $GITHUB_ENV
          mkdir -p ${HOME}/usr/bin
          mkdir -p ${HOME}/usr/lib
          mkdir -p ${HOME}/usr/include
          mkdir -p ${HOME}/usr/src

      - name: build milib
        run: |
          for lib in zeda zm zeo roki
          do
          git clone https://github.com/mi-lib/${lib}.git ${HOME}/usr/src/${lib}
          cd ${HOME}/usr/src/${lib} && make && make install
          done
        
      - name: build
        run: make && make install
